source "https://rubygems.org"

gem "fastlane"

# Fastlane eklentilerini (Pluginfile) otomatik yükle
plugins_path = File.join(File.dirname(__FILE__), "fastlane", "Pluginfile")
eval_gemfile(plugins_path) if File.exist?(plugins_path)
